#%RAML 1.0
title: consumer API
  
/consumers:
  get:
    queryParameters:
      choose:
        displayName: choose
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
            example:
              message: "The records are"
  
  post:
    queryParameters:
      choose:
        displayName: choose
        type: string
        required: true
    body:
      application/json:
        example: !include /examples/example.raml
    responses:
      201:
        body:
          application/json:
            example:
              message: "New record inserted successfully"    
  put:
    queryParameters:
      choose:
        displayName: choose
        type: string
        required: true
      name:
        displayName: name
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
            example:
              message: "Updated record successfully"
  delete:
    queryParameters:
      choose:
        displayName: choose
        type: string
        required: true
      name:
        displayName: name
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
            example:
              message: "Deleted record successfully"